---
- hosts: all
  become: true
  tasks:

  - name: update repository cache
    ansible.builtin.apt:
      update_cache: yes
#      cache_valid_time: 3600

  - name: Upgrade all packages to the latest version
    ansible.builtin.apt:
      upgrade: dist
      autoremove: yes
      autoclean: yes
      dpkg_options: 'force-confold,force-confdef'

  - name: Reboot if required
    ansible.builtin.reboot:
      msg: "Reboot initiated by Ansible for kernel upgrade"
      connect_timeout: 5
      reboot_timeout: 600
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: whoami

  - name: Ensure unattended-upgrades is installed
    ansible.builtin.apt:
      name: unattended-upgrades
      state: present
